### ISSUE TITLE
lean_delivery.minio/tasks/main.yml': line 65, column 3,

### ISSUE THREAD

**Issue by olegsidokhmetov** [lean-delivery/ansible-role-minio#4]
##### SUMMARY

ERROR! 'notify' is not a valid attribute for a TaskInclude

The error appears to be in '/etc/ansible/roles/lean_delivery.minio/tasks/main.yml': line 65, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: SSL preparation
  ^ here

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
```

##### CONFIGURATION

ansible-config dump --only-changed
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles']

##### OS / ENVIRONMENT

Ubuntu 20.04

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```
Parsed /etc/ansible/hosts inventory source with ini plugin
ERROR! 'notify' is not a valid attribute for a TaskInclude

The error appears to be in '/etc/ansible/roles/lean_delivery.minio/tasks/main.yml': line 65, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: SSL preparation
  ^ here
```

**Comment by pavelpikta** [comment]
Hi @olegsidokhmetov 
Thank you for your first issue

**Comment by olegsidokhmetov** [comment]
how to change this block, if I use Ubuntu?

- block:
    - name: Enable EPEL repository
      yum:
        name: 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
        state: present
      register: package_install
      until: package_install is succeeded
      when: ansible_os_family == 'Ubuntu'

**Comment by pavelpikta** [comment]
```yaml
    - name: Enable EPEL repository
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        state: present
      register: package_install
      until: package_install is succeeded
      when: ansible_os_family == 'RedHat'
````

This task will be run only on RedHat. On Ubuntu this task will be skipped
